server:
  port: 0
  servlet:
    context-path: /product-api
inventoryService: inventory
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
